version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: npm i
      - run: npm test
      - run: curl -s https://codecov.io/bash > ./codecov
      - run: chmod +x ./codecov
      - run: ./codecov -f "./src/tests/coverage/cobertura.xml" -t $CODECOV_TOKEN
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm i
      - run: npm run build
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm publish
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v\d\.\d\.\d/
            branches:
              ignore: /.*/
