version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: npm i
      - run: npm test
      - run: curl -s https://codecov.io/bash > ./codecov
      - run: chmod +x ./codecov
      - run: ./codecov -f "./src/tests/coverage/cobertura.xml" -t $CODECOV_TOKEN
